### ISSUE TITLE
Anzeige bei eigener gesendeter Nachricht.

### ISSUE THREAD

**Issue by NMA93** [logrinto/IAD2017.chat#12]
Als User möchte ich eigene Nachrichten in der Chat-Übersicht erkennen.

Beispiel:

**Empfangene Nachricht:**
Lorem Ipsum.

**Gesendete Nachricht:**
Du: Lorem Ipsum.

<img width="460" alt="Bildschirmfoto 2019-05-06 um 22 21 16" src="https://user-images.githubusercontent.com/23292494/57252774-4ee60180-704d-11e9-8b39-d9e2b8595456.png">

**Comment by signalwerk** [comment]
Ja das sollte eigentlich easy zu implementieren sein. Ich könnte ja eine CSS-Klasse hinzufügen, so dass man zwischen `me` und `others` unterscheiden kann. So könnten die Studierenden dann selber im CSS den Text hinzufügen (für die, die es möchten).

```css
.selektor::before {
  content: "Du:";
}
```
Ich habe nun eine Schätzung für die Implementierung dieses Issues abgegeben (siehe Tag). Am kommenden Freitag sprechen wir über die offenen Issues und entscheiden gemeinsam, welche Features als nächstes implementiert werden. Ich hoffe das ist ok für dich.

**Comment by signalwerk** [comment]
Es gibt nu neue Klassen, mit denen mas das machen kann:

```
css
.ConversationItem--me .ConversationItem__Preview > p::before {
  content: "Ich: ";
}

.ConversationItem--others .ConversationItem__Preview > p::before {
  content: "Du: ";
}
```
