### ISSUE TITLE
Send Button nur bei Eingabe sichtbar

### ISSUE THREAD

**Issue by NMA93** [logrinto/IAD2017.chat#14]
Als User möchte ich den Senden-Button nur bei der Eingabe sehen. Da dieser Button ohne Text keine Funktion hat und somit nicht gezeigt werden sollte. 

<img width="824" alt="Bildschirmfoto 2019-05-10 um 13 29 34" src="https://user-images.githubusercontent.com/23292494/57525586-6bbf5500-732b-11e9-911e-193390a1b290.png">

**Comment by signalwerk** [comment]
Es gibt nun auf `Conversation__Form` je nach status eine zusätzliche Klasse `Conversation__Form--text` oder `Conversation__Form--noText`. Somit kann mit einem Selektor:

```css 
.Conversation__Form--noText .Conversation__Send {
 display: none;
}
```
die Schaltfläche ausgeblendet werden oder aber das ganze layout vom Senden-Teil verändert werden
