### ISSUE TITLE
Senden per Enter

### ISSUE THREAD

**Issue by pascaleva** [logrinto/IAD2017.chat#4]
Als User möchte ich meine Nachricht per **Senden Button** sowie mit der **Enter-Taste** absenden können.

**Comment by signalwerk** [comment]
Merci für den Input und die Überlegung. Finde ich grundsätzlich gut. Es gibt aus meiner Erfahrung zwei arten von Chat-Clients. Die einen die auf «Enter» senden, die anderen die auf «NumpadEnter» senden. (https://keycode.info/)

Ich habe nun eine Schätzung für die Implementierung dieses Issues abgegeben (siehe Tag). Am kommenden Freitag sprechen wir über die offenen Issues und entscheiden gemeinsam, welche Features als nächstes implementiert werden. Ich hoffe das ist ok für dich.

**Comment by signalwerk** [comment]
ist nun online
