### ISSUE TITLE
Platzhaltertext bei Eingabefeld: Nachricht schreiben...

### ISSUE THREAD

**Issue by pascaleva** [logrinto/IAD2017.chat#5]
Im Chat soll im Eingabefeld ein Platzhaltertext mit: «Nachricht schreiben...» eingefügt werden. Dieser verschwindet, sobald man eine Eingabe macht.

**Comment by signalwerk** [comment]
Finde ich einen guten Hinweis und ist easy zu implementieren!

Ich habe nun eine Schätzung für die Implementierung dieses Issues abgegeben (siehe Tag). Am kommenden Freitag sprechen wir über die offenen Issues und entscheiden gemeinsam, welche Features als nächstes implementiert werden. Ich hoffe das ist ok für dich.

**Comment by signalwerk** [comment]
ist nun online
