### ISSUE TITLE
Startscreen

### ISSUE THREAD

**Issue by stfffchs** [logrinto/IAD2017.chat#7]
Beim Öffnen des Chats ist die letzte Konversation offen (sichtbar). Ein leerer Konversationsraum ist nicht möglich.

**Comment by NMA93** [comment]
@stfffchs Kannst du das genauer definieren? Mir ist nicht klar was du genau meinst. 

Öffnet sich automatisch immer die letzte Konversation? 
Ein leerer Konversationsraum ist aus meiner Sicht eigentlich möglich, bei Eröffnung eines neuen Chats?

**Comment by stfffchs** [comment]
@NMA93 
Genau > es soll sich immer der letzte Chat öffnen. Wenn ich den Messenger öffne ist ein leerer KR überflüssig – bringt ja nichts. Der KR soll nur bei Eröffnung eines neuen Chats leer sein.

**Comment by signalwerk** [comment]
@stfffchs @NMA93 Ich habe einen kleinen Einwand: wenn ich einen Chat-Client öffne, möchte ich nicht, dass meine letzte Konversation auf geht und die Messages somit als gelesen Markiert werden. Das kann sowohl für mich ungünstig sein, da ich im Moment allenfalls gar keine Zeit habe mich darum zu kümmern und dann aber die Markierung verliere, dass da was unbeantwortet ist. Und andererseits zeigt es (je nach Client) dann dem Gegenüber an, dass ich die Nachricht gelesen habe und diese Person wundert sich, warum ich nicht eeeennndlich antworte. 
So wie es jetzt implementiert ist, geht ein Start-Screen auf in dem der Programmname steht. Dieser Screen sieht einfach noch nicht nach Startscreen aus...

Ich habe für den kommenden Donnerstag eine kleine Übersicht offenere Punkte gemacht und habe gerne auch diesen Punkt in die Diskussion aufgenommen, damit wir sehen was die anderen «Product Owner» der Klasse sagen 🤓
