### ISSUE TITLE
Reihenfolge Chats

### ISSUE THREAD

**Issue by stfffchs** [logrinto/IAD2017.chat#8]
Sobald man eine Nachricht geschrieben hat (oder erhält), wird dieser Chat an die oberste Stelle geschoben. Der aktuellste Chat muss zuoberst sein.

**Comment by signalwerk** [comment]
👌unbedingt!

Ich habe nun eine Schätzung für die Implementierung dieses Issues abgegeben (siehe Tag). Am kommenden Freitag sprechen wir über die offenen Issues und entscheiden gemeinsam, welche Features als nächstes implementiert werden. Ich hoffe das ist ok für dich.

**Comment by signalwerk** [comment]
online! ✨
