### ISSUE TITLE
Unterschiedliche Zeiten

### ISSUE THREAD

**Issue by pascaleva** [logrinto/IAD2017.chat#9]
Zeiten der bereits gesendeten Nachrichten sollen verschieden sein (nicht nur 12:00) und schön wäre es wenn die aktuelle Zeit erscheint wenn neue Nachrichten geschrieben werden (optional).

**Comment by signalwerk** [comment]
Joa kann ich machen. Ist bei meinem Test-Daten-Generator noch nicht vorgesehen gewesen. Wir sollten dann allenfalls aber auch noch besprechen, dass es zwischen den Tagen auch noch zusätzlich einen Trenner mit dem Datum gibt:

```
21:52 – Clara – Kommst du noch in die Mars Bar?

[[25. Dezember 2018]]  ← Datum-Trenner

01:15 – Hans – Ne Sorry ich muss beim Hamster bleiben. Der hat Bauchweh. 😢
```




Ich habe nun eine Schätzung für die Implementierung dieses Issues abgegeben (siehe Tag). Am kommenden Freitag sprechen wir über die offenen Issues und entscheiden gemeinsam, welche Features als nächstes implementiert werden. Ich hoffe das ist ok für dich.

**Comment by signalwerk** [comment]
online! ✨
